apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
    name: test-comp
    projectName: TestCP3
spec:
    build:
        branch: main
    inbound:
        - name: test-comp
          port: 9090
          type: REST
          visibility: Public
          context: .
